name: Extension Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
    
    steps:
    - uses: actions/checkout@v6

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build
    
    - name: Check Circular Dependencies
      run: |
        npx --yes madge --circular --extensions ts ./
