name: Extension Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [24.x]
    
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Build and compress
        run: |
          TAG=${{ github.ref_name }}
          npm ci
          npm run build
          (cd dist && zip -r ../extension-${TAG}-chrome.zip .)
          rm -rf dist
          npm run build_ff
          (cd dist && zip -r ../extension-${TAG}-firefox.zip .)

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            extension-*-chrome.zip
            extension-*-firefox.zip
