name: "Submit to Firefox Add-ons Store"
on:
    workflow_run:
        workflows: ["Extension Release"]
        types:
            - completed
    # Allow manual triggering from the GitHub Actions UI
    workflow_dispatch:

jobs:
    submit:
      runs-on: "ubuntu-latest"
  
      steps:
        - uses: actions/checkout@v3
  
        - name: Compress Repository
          run: |
            zip -r extension-source.zip .

        - name: Download Release Assets
          uses: robinraju/release-downloader@v1
          with:
            latest: true # Download the latest release
            out-file-path: "assets" # Output directory for downloaded assets
            fileName: '*' # Download all assets
            
        - name: Find Extension Path
          id: find-path
          # Find and output the path to the extension zip
          # Required as the release action does not support glob patterns
          run: |
            FIREFOX_EXT_PATH=$(find assets -name "extension-*-firefox.zip" | head -n 1)
            echo "firefox_extension_path=$FIREFOX_EXT_PATH" >> $GITHUB_OUTPUT

        - name: Firefox Web Store Publish
          uses: browser-actions/release-firefox-addon@v0.2.1
          with:
            addon-id: ${{ secrets.FIREFOX_EXTENSION_ID }}
            addon-path: ${{ steps.find-path.outputs.firefox_extension_path }}
            source-path: "extension-source.zip"
            approval-note: |
              The source code and build instructions are available at 
              https://github.com/csfloat/extension?tab=readme-ov-file#how-to-build-release.
            auth-api-issuer: ${{ secrets.AUTH_API_ISSUER }}
            auth-api-secret: ${{ secrets.AUTH_API_SECRET }}